name: main
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
      
    steps:
      - name: Check out code
        uses: actions/checkout@v2
          
      - name: Build Docker image
        run: docker build -t nags .
        
      - name: Run Docker container
        run: docker run -d -p 8080:8080 nags
        
      - name: Show Docker Images
        run: docker images   
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}-${{steps.vars.outputs.stage}}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      
      - name: Tag Docker image
        run: docker tag nags:latest.dkr.ecr.us-east-1.amazonaws.com/webserver:new 
      
      - name: Push Docker image to ECR
        run: docker push public.ecr.aws/n8y3z0e0/webserver:new
